server:
  port: 8082
  servlet:
    session:
      timeout: 15m
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=training_service
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      username: postgres
      password: postgres
      connection-timeout: 10000
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 60000
      max-lifetime: 180000
      auto-commit: true
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: training_service
        format_sql: true
        jdbc:
          batch_size: 15
          fetch_size: 90
        max_fetch_depth: 3
        generate_statistics: false
        temp:
          use_jdbc_metadata_defaults: true
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-root.yml
    liquibase-schema: training_service_liquibase
    default-schema: training_service
    drop-first: false
logging:
  config: classpath:logback-spring.xml
